"""
NGAFID-MC ingest and preprocessing.

The corpus is 5.4 GB of 1 Hz Parquet (Zenodo 6624956, CC-BY-4.0) and is not
bundled with this repository - the whole point of the adapter layer is that the
corpus is swappable. Point ``AEROTWIN_NGAFID_DIR`` at a directory of Parquet or
CSV flight files and this module reports on what it actually found: which
columns mapped, which are missing, how much of each channel is null.

Nothing here invents a column. If a channel is absent from the file it is
reported ABSENT, and the twin either derives it from physics (tagged
SIMULATED) or does without it.
"""

from __future__ import annotations

import csv
import math
from dataclasses import dataclass, field
from pathlib import Path

from ..core.constants import CHANNELS, DATASET_NGAFID
from ..sources.ngafid import (COLUMN_ALIASES, corpus_mode, dataset_dir,
                              discover_flights)

# --------------------------------------------------------------------------
# Data dictionary - what the twin expects, where it comes from, what it means
# --------------------------------------------------------------------------

_SOURCE_NOTE = {
    "REAL": (
        "Measured channel. Read from the corpus at 1 Hz, or reproduced by the "
        "demo telemetry simulator against the identical contract."
    ),
    "SIMULATED": (
        "No real counterpart in NGAFID-MC. Generated by the physics model and "
        "tagged SIMULATED at every layer."
    ),
}

_ALIAS_BY_KEY: dict[str, list[str]] = {}
for _raw, _key in COLUMN_ALIASES.items():
    if not _key.startswith("_"):
        _ALIAS_BY_KEY.setdefault(_key, []).append(_raw)

_RANGES: dict[str, tuple[float, float]] = {
    "rpm": (0.0, 3200.0),
    "map_inhg": (5.0, 32.0),
    "fuel_flow_gph": (0.0, 26.0),
    "egt_1": (150.0, 900.0), "egt_2": (150.0, 900.0),
    "egt_3": (150.0, 900.0), "egt_4": (150.0, 900.0),
    "cht_1": (20.0, 290.0), "cht_2": (20.0, 290.0),
    "cht_3": (20.0, 290.0), "cht_4": (20.0, 290.0),
    "oil_press_psi": (0.0, 110.0),
    "oil_temp_c": (-20.0, 135.0),
    "oat_c": (-60.0, 55.0),
    "altitude_ft": (-1000.0, 30000.0),
    "ias_kt": (0.0, 220.0),
    "vibration_g": (0.0, 6.0),
    "inj_timing_deg": (0.0, 45.0),
}

_PHYSICS_INPUTS = ("altitude_ft", "oat_c", "ias_kt")

DATA_DICTIONARY: list[dict] = [
    {
        "key": channel["key"],
        "label": channel["label"],
        "unit": channel["unit"],
        "group": channel["group"],
        "provenance": channel["provenance"],
        "per_cylinder": channel["per_cylinder"],
        "corpus_columns": _ALIAS_BY_KEY.get(channel["key"], []),
        "valid_range": list(_RANGES[channel["key"]]) if channel["key"] in _RANGES else None,
        "rate_hz": 1.0,
        "role": "PHYSICS INPUT" if channel["key"] in _PHYSICS_INPUTS else "RESIDUAL CHANNEL",
        "note": channel["note"],
        "source_note": _SOURCE_NOTE[channel["provenance"]],
    }
    for channel in CHANNELS
]

DATA_DICTIONARY_NOTE = (
    "The twin's data contract. Sixteen channels are measured, two are generated "
    "by the physics model because NGAFID-MC carries no accelerometer and "
    "publishes no injection timing. Any adapter that satisfies this contract - "
    "an authorised test-rig export, a live CAN feed - drops into the same slot "
    "with no change downstream."
)


# --------------------------------------------------------------------------
# Cleaning
# --------------------------------------------------------------------------

def clean_value(key: str, value: float | None) -> float | None:
    """Range-gate a single sample. Out-of-range becomes None, never a guess."""
    if value is None:
        return None
    try:
        v = float(value)
    except (TypeError, ValueError):
        return None
    if math.isnan(v) or math.isinf(v):
        return None
    bounds = _RANGES.get(key)
    if bounds and not (bounds[0] <= v <= bounds[1]):
        return None
    return v


def interpolate_gaps(series: list, max_gap: int = 5) -> list:
    """Linear fill of short gaps only.

    A 1 Hz sensor dropping three samples is a dropout; filling it is reasonable.
    A sixty-second hole is a different flight condition and must stay a hole,
    otherwise the residual is computed against fabricated observations.
    """
    out = list(series)
    n = len(out)
    i = 0
    while i < n:
        if out[i] is not None:
            i += 1
            continue
        start = i
        while i < n and out[i] is None:
            i += 1
        end = i
        gap = end - start
        if gap > max_gap or start == 0 or end >= n:
            continue
        left, right = out[start - 1], out[end]
        if left is None or right is None:
            continue
        for j in range(start, end):
            u = (j - start + 1) / (gap + 1)
            out[j] = left + (right - left) * u
    return out


# --------------------------------------------------------------------------
# Corpus inspection
# --------------------------------------------------------------------------

@dataclass
class ColumnReport:
    key: str
    matched_column: str | None
    present: bool
    null_pct: float
    minimum: float | None
    maximum: float | None
    mean: float | None

    def as_dict(self) -> dict:
        return {
            "key": self.key,
            "matched_column": self.matched_column,
            "status": "MAPPED" if self.present else "ABSENT",
            "null_pct": round(self.null_pct, 2),
            "min": round(self.minimum, 2) if self.minimum is not None else None,
            "max": round(self.maximum, 2) if self.maximum is not None else None,
            "mean": round(self.mean, 2) if self.mean is not None else None,
        }


@dataclass
class IngestReport:
    configured: bool
    directory: str | None
    files: int
    inspected_file: str | None
    rows: int
    columns: list = field(default_factory=list)
    raw_columns: list = field(default_factory=list)
    unmapped_columns: list = field(default_factory=list)
    parquet_supported: bool = False
    #: Parquet flight files were found, so the reader is no longer optional.
    parquet_needed: bool = False
    #: Which corpus is mounted: REAL (operator), DEMO (bundled), ABSENT.
    mode: str = "ABSENT"
    #: ACTIVE | CONNECTED | CONFIGURATION REQUIRED | LOAD FAILED
    state: str = "ACTIVE"
    messages: list = field(default_factory=list)

    @property
    def status(self) -> str:
        if self.mode == "REAL":
            return "CONNECTED"
        if self.mode == "DEMO":
            return "ACTIVE"
        return "NOT CONFIGURED"

    @property
    def parquet_state(self) -> str:
        """
        Parquet is one of two readers, not a requirement.

        It is only REQUIRED when Parquet flight files are actually present and
        cannot be opened - which is a real configuration problem. With CSV
        flights, or none at all, an absent Parquet reader is not a fault and
        must not be reported as one.
        """
        if self.parquet_supported:
            return "READY"
        return "REQUIRED" if self.parquet_needed else "OPTIONAL"

    def as_dict(self) -> dict:
        mapped = sum(1 for c in self.columns if c.present)
        return {
            "configured": self.configured,
            "mode": self.mode,
            "state": self.state,
            # Provenance of what is mounted, so a badge renders straight from
            # the report rather than re-deriving it in the client.
            "provenance": "REAL" if self.mode == "REAL" else "DEMO",
            "directory": self.directory,
            "files": self.files,
            "inspected_file": self.inspected_file,
            "rows": self.rows,
            "rate_hz": 1.0,
            "required_channels": len(self.columns),
            "mapped_channels": mapped,
            "columns": [c.as_dict() for c in self.columns],
            "raw_columns": self.raw_columns,
            "unmapped_columns": self.unmapped_columns,
            "parquet": self.parquet_state,
            "parquet_supported": self.parquet_supported,
            "messages": self.messages,
            "status": self.status,
            "dataset": DATASET_NGAFID,
        }


def _parquet_supported() -> bool:
    try:
        import pyarrow  # noqa: F401
        return True
    except Exception:
        try:
            import fastparquet  # noqa: F401
            return True
        except Exception:
            return False


class NgafidPreprocessor:
    """Inspects a mounted corpus and reports what actually mapped."""

    SAMPLE_ROWS = 4000

    def inspect(self) -> IngestReport:
        root = dataset_dir()
        files = discover_flights()
        mode = corpus_mode()
        report = IngestReport(
            configured=root is not None,
            mode=mode,
            directory=str(root) if root else None,
            files=len(files),
            inspected_file=None,
            rows=0,
            parquet_supported=_parquet_supported(),
            parquet_needed=any(f.lower().endswith(".parquet") for f in files),
        )

        if root is None or not files:
            # Nothing to read anywhere, bundled corpus included. This is the
            # only genuinely unconfigured case and the only one that should ask
            # the operator to do something.
            report.state = "CONFIGURATION REQUIRED"
            report.columns = [
                ColumnReport(c["key"], None, False, 100.0, None, None, None)
                for c in CHANNELS if c["provenance"] == "REAL"
            ]
            return report

        target = next((f for f in files if f.lower().endswith(".csv")), files[0])
        path = root / target
        report.inspected_file = target

        if path.suffix.lower() == ".parquet" and not report.parquet_supported:
            report.state = "CONFIGURATION REQUIRED"
            report.messages.append("PARQUET READER UNAVAILABLE - INSTALL pyarrow OR USE CSV")
            return report

        try:
            rows, raw_columns = self._read(path)
        except Exception as exc:                     # pragma: no cover - IO guard
            report.state = "LOAD FAILED"
            report.messages.append("COULD NOT READ " + target)
            report.messages.append(str(exc))
            return report

        report.rows = len(rows)
        report.raw_columns = raw_columns
        mapped_raw = {c for c in raw_columns if c in COLUMN_ALIASES}
        report.unmapped_columns = sorted(set(raw_columns) - mapped_raw)

        for channel in CHANNELS:
            if channel["provenance"] != "REAL":
                continue
            key = channel["key"]
            matched = next((c for c in raw_columns if COLUMN_ALIASES.get(c) == key), None)
            if matched is None:
                report.columns.append(ColumnReport(key, None, False, 100.0, None, None, None))
                continue
            values = [clean_value(key, r.get(matched)) for r in rows]
            good = [v for v in values if v is not None]
            null_pct = 100.0 * (1.0 - len(good) / max(1, len(values)))
            report.columns.append(ColumnReport(
                key=key,
                matched_column=matched,
                present=True,
                null_pct=null_pct,
                minimum=min(good) if good else None,
                maximum=max(good) if good else None,
                mean=sum(good) / len(good) if good else None,
            ))

        report.state = "CONNECTED" if mode == "REAL" else "ACTIVE"
        return report

    def _read(self, path: Path):
        if path.suffix.lower() == ".csv":
            with path.open("r", newline="", encoding="utf-8", errors="replace") as fh:
                reader = csv.DictReader(fh)
                columns = list(reader.fieldnames or [])
                rows = []
                for i, row in enumerate(reader):
                    if i >= self.SAMPLE_ROWS:
                        break
                    rows.append(row)
            return rows, columns

        import pandas as pd                            # deferred: optional dep
        frame = pd.read_parquet(path)
        columns = [str(c) for c in frame.columns]
        rows = frame.head(self.SAMPLE_ROWS).to_dict(orient="records")
        return rows, columns


_preprocessor = NgafidPreprocessor()
_cached: IngestReport | None = None


def ingest_report(refresh: bool = False) -> dict:
    global _cached
    if _cached is None or refresh:
        _cached = _preprocessor.inspect()
    return _cached.as_dict()
