/**
 * Live telemetry.
 *
 * The channel table is where provenance is enforced most visibly: sixteen
 * measured channels and two generated by the physics model, each tagged, with
 * the reason a generated channel exists stated inline. A simulated channel is
 * never presented as a measurement.
 */

import { Fragment, useEffect, useMemo, useState } from 'react'
import { Activity, Radio, Waves } from 'lucide-react'
import { api } from '../services/api'
import { useTwin } from '../store/useTwin'
import { ExpectedActualChart, ResidualChart, Sparkline } from '../components/charts/Charts'
import {
  Badge, Empty, Note, PageHead, ProvenanceTag, Stat, fmt, signed,
} from '../components/ui/Primitives'
import type { Channel } from '../types'

const GROUP_ORDER = ['OPERATING POINT', 'COMBUSTION', 'THERMAL', 'LUBRICATION', 'MECHANICAL', 'AMBIENT']

export default function Telemetry() {
  const telemetry = useTwin((s) => s.telemetry)
  const residuals = useTwin((s) => s.residuals)
  const history = useTwin((s) => s.history)
  const mode = useTwin((s) => s.mode)

  const [channels, setChannels] = useState<Channel[]>([])
  const [summary, setSummary] = useState<any>(null)
  const [note, setNote] = useState<string>('')
  const [focus, setFocus] = useState('cht_3')

  useEffect(() => {
    void api.channels().then((data) => {
      if (!data) return
      setChannels(data.channels ?? [])
      setSummary(data.summary)
      setNote(data.note ?? '')
    })
  }, [])

  const grouped = useMemo(() => {
    const map = new Map<string, Channel[]>()
    for (const channel of channels) {
      const list = map.get(channel.group) ?? []
      list.push(channel)
      map.set(channel.group, list)
    }
    return GROUP_ORDER.filter((g) => map.has(g)).map((g) => [g, map.get(g)!] as const)
  }, [channels])

  const focusChannel = channels.find((c) => c.key === focus)
  const focusSeries = history[focus] ?? []
  const source = telemetry?.source

  return (
    <>
      <PageHead
        title="Telemetry"
        actions={
          <div className="row row--tight">
            <Badge tone={mode === 'DEMO' ? 'demo' : 'ok'} dot live>
              {source?.label ?? (mode === 'DEMO' ? 'LOCAL DEMO GENERATOR' : 'STREAM ACTIVE')}
            </Badge>
            {/* The live counts, not the contract's. On the simulator every
                measurable channel is being produced, not measured. */}
            {(summary?.real ?? 0) > 0 && <Badge tone="real">{summary.real} REAL</Badge>}
            {(summary?.demo ?? 0) > 0 && <Badge tone="demo">{summary.demo} DEMO</Badge>}
            <Badge tone="sim">{summary?.simulated ?? 2} SIMULATED</Badge>
          </div>
        }
      />

      {source && (
        <section className="panel" style={{ marginBottom: 16 }}>
          <div className="panel__body panel__body--tight">
            <div className="row" style={{ alignItems: 'flex-start' }}>
              <Radio size={15} color="var(--accent-ink)" style={{ marginTop: 2 }} />
              <div style={{ minWidth: 0 }}>
                <div className="row row--tight" style={{ marginBottom: 3 }}>
                  <span className="label" style={{ color: 'var(--ink-2)' }}>{source.label}</span>
                  <ProvenanceTag provenance={source.provenance} />
                  <Badge>{source.kind}</Badge>
                  <Badge>{source.rate_hz} Hz</Badge>
                </div>
              </div>
            </div>
          </div>
        </section>
      )}

      <div className="grid" style={{ gridTemplateColumns: 'minmax(0, 1.25fr) minmax(0, 1fr)', marginBottom: 16 }}>
        <section className="panel">
          <header className="panel__head">
            <Activity size={13} color="var(--accent-ink)" />
            <h2 className="panel__title">Channel table</h2>
            <span className="panel__sub">CLICK TO CHART</span>
            <span className="panel__spacer" />
            <span className="mono" style={{ fontSize: 11.5, color: 'var(--ink-4)' }}>
              t = {fmt(telemetry?.tick?.t, 0)} s
            </span>
          </header>
          <div className="panel__body panel__body--flush">
            <div className="scroll-y" style={{ maxHeight: 452 }}>
              <table className="table table--compact">
                <thead>
                  <tr>
                    <th>Channel</th>
                    <th className="num">Value</th>
                    <th className="num">Expected</th>
                    <th className="num">Residual</th>
                    <th style={{ width: 74 }}>Trend</th>
                    <th>Provenance</th>
                  </tr>
                </thead>
                <tbody>
                  {grouped.map(([group, list]) => (
                    <Fragment key={group}>
                      <tr>
                        <td colSpan={6} style={{ background: 'var(--panel-3)', padding: '5px 12px' }}>
                          <span className="micro" style={{ color: 'var(--ink-4)' }}>{group}</span>
                        </td>
                      </tr>
                      {list.map((channel) => {
                        const value = telemetry?.tick?.channels?.[channel.key]
                        const expected = telemetry?.tick?.expected?.[channel.key]
                        const residual = residuals?.channels?.[channel.key]
                        const series = (history[channel.key] ?? []).slice(-40).map((p) => p.observed)
                        return (
                          <tr
                            key={channel.key}
                            onClick={() => residual && setFocus(channel.key)}
                            style={{
                              cursor: residual ? 'pointer' : 'default',
                              background: focus === channel.key ? 'rgba(10,110,214,0.06)' : undefined,
                            }}
                          >
                            <td>{channel.label}</td>
                            <td className="num">
                              {value !== undefined ? `${fmt(value, 1)} ${channel.unit}` : '—'}
                            </td>
                            <td className="num" style={{ color: 'var(--expected-ink)' }}>
                              {expected !== undefined ? fmt(expected, 1) : '—'}
                            </td>
                            <td className="num" style={{ color: 'var(--residual-ink)' }}>
                              {residual ? signed(residual.residual, 2) : '—'}
                            </td>
                            <td style={{ padding: 0 }}>
                              {series.length > 3 && (
                                <Sparkline
                                  values={series}
                                  height={26}
                                  color={channel.provenance === 'SIMULATED' ? '#7739e0' : '#0a6ed6'}
                                />
                              )}
                            </td>
                            <td>
                              <ProvenanceTag provenance={channel.provenance} title={channel.note} />
                            </td>
                          </tr>
                        )
                      })}
                    </Fragment>
                  ))}
                  {!channels.length && (
                    <tr>
                      <td colSpan={6}>
                        <Empty label="Awaiting channel registry" />
                      </td>
                    </tr>
                  )}
                </tbody>
              </table>
            </div>
          </div>
        </section>

        <section className="panel">
          <header className="panel__head">
            <Waves size={13} color="var(--accent-ink)" />
            <h2 className="panel__title">{focusChannel?.label ?? focus}</h2>
            <span className="panel__spacer" />
            {focusChannel && <ProvenanceTag provenance={focusChannel.provenance} />}
          </header>
          <div className="panel__body panel__body--tight">
            {focusSeries.length > 3 ? (
              <>
                <ExpectedActualChart series={focusSeries} unit={focusChannel?.unit ?? ''} height={180} />
                <ResidualChart series={focusSeries} unit={focusChannel?.unit ?? ''} height={120} />
              </>
            ) : (
              <div className="skeleton" style={{ height: 300 }} />
            )}
          </div>
        </section>
      </div>

      <div className="grid grid--4" style={{ marginBottom: 16, marginRight: 372 }}>
        {['rpm', 'map_inhg', 'oil_press_psi', 'fuel_flow_gph'].map((key) => {
          const channel = channels.find((c) => c.key === key)
          const series = history[key] ?? []
          const value = telemetry?.tick?.channels?.[key]
          return (
            <section className="panel" key={key}>
              <header className="panel__head">
                <h2 className="panel__title">{channel?.label ?? key.toUpperCase()}</h2>
                <span className="panel__spacer" />
                {channel && <ProvenanceTag provenance={channel.provenance} />}
              </header>
              <div className="panel__body panel__body--tight">
                <Stat
                  k="Current"
                  v={fmt(value, 1)}
                  unit={channel?.unit}
                  size="lg"
                />
                {series.length > 3 && <ExpectedActualChart series={series} unit={channel?.unit ?? ''} height={120} />}
              </div>
            </section>
          )
        })}
      </div>

      {note && (
        <div style={{ marginRight: 372 }}>
          <Note tone="info">{note}</Note>
        </div>
      )}
    </>
  )
}
